In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
result = arr ** 2
result

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [3]:
result + 10

array([11, 14, 19, 26, 35, 46, 59, 74])

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr1 = np.array([1,2,3,4,5,6])

In [6]:
arr2 = np.array([8,7,5,45,6,8])

In [7]:
arr2 + arr1

array([ 9,  9,  8, 49, 11, 14])

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [10]:
arr2 = np.array([1,5,6])

In [11]:
arr1 + arr2 # Broadcasting arr2 across arr1

array([[ 2,  7,  9],
       [ 5, 10, 12]])

In [12]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
# calculating mean and standard deviation for each feature (column)
mean = data.mean(axis = 0)
mean
                 

array([20., 30., 40.])

In [13]:
std = data.std(axis=0)
std

array([7.07106781, 7.07106781, 7.07106781])

In [14]:
normalized_data = (data-mean) 

In [15]:
normalized_data


array([[-10., -10., -10.],
       [ -5.,  -5.,  -5.],
       [  0.,   0.,   0.],
       [  5.,   5.,   5.],
       [ 10.,  10.,  10.]])

In [16]:
normalized_data = normalized_data / std

In [17]:
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])