In [1]:
import numpy as np
arr = np.array([1,2,4])
arr


array([1, 2, 4])

In [2]:
np.zeros((3,4)) # 3*4 arrays of zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4)) # 3*4 arrays of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((3,4),6) # 3*4 arrays filled with 6

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [5]:
np.eye(5) # 5*5 identity matrix


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.arange(1,10,3) # [1, 4, 7] like range

array([1, 4, 7])

In [7]:
np.linspace(0,1.9,5) # [0.  , 0.25, 0.5 , 0.75, 1.  ] evenly spaced

array([0.   , 0.475, 0.95 , 1.425, 1.9  ])

In [8]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [9]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [10]:
myarr.shape


(4, 3)

In [11]:
myarr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [12]:
myarr.size

12

In [13]:
myarr.ndim

2

In [21]:
myarr.dtype


dtype('int64')

In [22]:
myarr.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [1]:
myarr

NameError: name 'myarr' is not defined