In [2]:
import numpy as np
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [5]:
flat = myarr.flatten()
flat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
b= flat[2:6]


In [11]:
b

array([3, 4, 5, 6])

In [12]:
b [0] = 278723

In [13]:
flat

array([     1,      2, 278723,      4,      5,      6,      7,      8,
            9,     11,     12,     13])

In [20]:
b= flat[2:6].copy()

In [21]:
b [0] = 27
b

array([27,  4,  5,  6])

In [22]:
a

[9277, 3, 4, 5, 6, 7, 8, 9]

In [23]:
# Fancy Indexing

arr = np.array([2,3,4,5,6,7,8,9,90])
arr[[1,2,3]]


array([3, 4, 5])

In [24]:
# Boolean Masking (filter Data)
arr = np.array([10,20,30,40,50])
mask = arr > 25 # condition : values greater than 25
arr[mask]


array([30, 40, 50])