### Built in Mathematical functions in numpy
##### Here are some common NumPy methods that are frequently used for statistical and mathematical operations:
1 . **np.mean()** = Compare the mean (average) of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.mean(arr)\
2. **np.std()** = Compare the standard deviation of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.std(arr)\
3. **np.var()** = Compare the variance of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.var(arr)\
4. **np.min()** = Compare the minimum value of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.min(arr)\
5. **np.max()** = Compare the maximum value of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.max(arr)\
6. **np.sum()** = Compare the sum of all elements of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.sum(arr)\
7. **np.prod()** = Compare the product of all elements of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.prod(arr)\
8. **np.median()** = Compare the median of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.median(arr)\
9. **np.percentile()** = Compare the percentile of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.percentile(arr, 50)\
10. **np.argmin()** = Return the index of the minimum value in an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.argmin(arr)\
11. **np.argmax()** = Return the index of the maximum value in an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.argmax(arr)\
12. **np.corrcoef()** = Compute the correlation coefficient matrix of two arrays. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.corrcoef(arr1, arr2)\
13. **np.unique()** = Find the unique elements of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.unique(arr)\
14. **np.diff()** = Compute the n-th differences of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.diff(arr)\
15. **np.cumsum()** = Compute the cumulative sum of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.cumsum(arr)\
16. **np.linspace()** = Create an array with evenly spaced numbers over a specified interval. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.linspace(0, 10, 5)  # 5 numbers from 0 to 10\
17. **np.log()** = Compute the natural logarithm of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.log(arr)\
18. **np.exp()** = Compute the exponential of an array. \
    &nbsp;&nbsp;&nbsp;&nbsp;np.exp(arr)

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
np.mean(arr)

np.float64(3.0)

In [3]:
np.min(arr)

np.int64(1)

In [4]:
np.max(arr)

np.int64(5)

In [5]:
np.std(arr)

np.float64(1.4142135623730951)

In [6]:
np.var(arr)

np.float64(2.0)

In [7]:
np.sum(arr)

np.int64(15)

In [8]:
np.prod(arr)

np.int64(120)

In [9]:
np.median(arr)

np.float64(3.0)

In [10]:
np.percentile(arr, 50)

np.float64(3.0)

In [11]:
np.argmin(arr)

np.int64(0)

In [12]:
np.argmax(arr)

np.int64(4)

In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,10,6,7,8])

np.corrcoef(arr1, arr2)

array([[ 1.        , -0.68624357],
       [-0.68624357,  1.        ]])

In [16]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [17]:
np.diff(arr)

array([1, 1, 1, 1])

In [18]:
 np.cumsum(arr)

array([ 1,  3,  6, 10, 15])