In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr[0]

array([1, 2, 3])

In [3]:
arr[0][0]

np.int64(1)

In [4]:
np.sum(arr , axis = 0)

array([12, 15, 18])

In [5]:
np.sum(arr , axis = 1)

array([ 6, 15, 24])

In [7]:
arr[0,1]

np.int64(2)

In [9]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [10]:
arr3d = np.array([[[1,2 ,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr3d.shape

# Output of arr3D.shape is → (depth, rows, columns)

(2, 2, 3)

In [12]:
print(arr3d[0, 1, 2]) 

6


In [13]:
print(arr3d[:, 0, :]) 

[[1 2 3]
 [7 8 9]]
